name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: install
        run: npm install mustache
      - name: Generate README file
        run: node index.js
        env:
          OPEN_WEATHER_MAP_KEY: ${{secrets.OPEN_WEATHER_MAP_KEY}}
      - name: working directory 
        run: echo "${{ github.workspace }}
      - name: Commit and Push new README.md to the repository
        uses: simpleprogrammer2/simpleprogrammer2@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   

          
