name: README build

on:
  push:
    branches:
      - main
      - main-test
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
      - name: Test
        run: echo "Hello, ${{ secrets.TEST }} "
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: install
        run: npm install mustache
        
      - name: Print all environment variables
        run: printenv
      - name: Generate README file
        run: |-
          node index.js

      - name: Commit and push new README.md
        run: |-
          git diff
          git config --global user.email ${{secrets.GLOBAL_USER_EMAIL}}
          git config --global user.name ${{secrets.GLOBAL_USER_NAME}}
          git commit -a -m "Hourly content update" || exit 0
          git push
   

          
