name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
        env:
          OPEN_WEATHER_MAP_KEY: ${{secrets.OPEN_WEATHER_MAP_KEY}}
      - name: Run another script
        run: ls
      - name: tet
        run: cd /home/runner/work/_actions/
      - name: test
        run: ls
      - name: Find files matching "*.rs" or "*.md"
        uses: jeertmans/filesfinder@latest
        id: ff # Any id, to be used later to reference to files output
        with:
          # Only argument, a single string, to be passed as arguments to ff.
          # See `ff --help` for more help.
          # Default: "*"
          args: "mustache.js"
      - name: Print files
        run: echo "${{ steps.ff.outputs.files }}"
      - name: working directory 
        run: echo "${{ github.workspace }}
      - name: copy mustache file
        run: cp node_modules/mustache/mustache.js node_modules/.bin/mustache
      - name: Commit and Push new README.md to the repository
        uses: simpleprogrammer2/simpleprogrammer2@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
